name: Build/test

on: workflow_dispatch

jobs:
  release:
    runs-on: windows-2019

    strategy:
      matrix:
        #os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest, windows-2019, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Electron Builder Action
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          windows_certs: ${{ secrets.WIN_CSC_LINK }}
          windows_certs_password: ${{ secrets.WIN_CSC_PASSWORD }}
          release: false
          # release: ${{ startsWith(github.ref, 'refs/tags/v') }}

        env:
          # macOS notarization API key
          API_KEY_ID: ${{ secrets.api_key_id }}
          API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}
